blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/dcdao/discussions
    about: Please ask and answer questions here.
  - name: Discord Server
    url: https://discord.com/invite/aQdK9H4MZS
    about: Join discord and chat with us.