blank_issues_enabled: false
contact_links:
  - name: Apply New DCDAO Profile
    url: https://github.com/dcdao/profiles/issues/new?assignees=&labels=application&template=application-template.md&title=%5BApplication%5D+
    about: Apply new dcdao profle
  - name: GitHub Community Support
    url: https://github.com/orgs/dcdao/discussions
    about: Please ask and answer questions here.