name: Upload NFT and Metadata
env:
  NFT_STORAGE_TOKEN: ${{ secrets.NFT_STORAGE_TOKEN }}

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
    paths:
      - 'release.md'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email ""

      - name: Upload to ipfs
        run: |
          npm install
          npm run start upload-ipfs

      - name: Commit
        run: |
          git add .
          git commit -m "Update ipfs address"
          git push
