name: Upload NFT and Metadata
env:
  PINATA_TOKEN: ${{ secrets.PINATA_TOKEN }}

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main
    paths:
      - 'release.md'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Prepare
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email ""
          git fetch --all
          git checkout release
          git pull

      - name: Upload to ipfs
        run: |
          npm install
          npm run start upload

      - name: Commit
        run: |
          git add .
          git commit -m "Update ipfs address"
          git push
